// Parses every lesson_*.tsx file in ../course_react_native into a
// single lessons-data.js file the static site loads as <script>.
// Re-run this any time a lesson file changes: node build.js

const fs = require("fs");
const path = require("path");

const SRC_DIR = path.join(__dirname, "..", "course_react_native");
const OUT_FILE = path.join(__dirname, "lessons-data.js");

const SECTIONS = [
  { from: 0, to: 14, name: "Fundamentals", color: "blue" },
  { from: 15, to: 18, name: "Advanced Hooks", color: "purple" },
  { from: 19, to: 20, name: "State Management", color: "pink" },
  { from: 21, to: 26, name: "Backend Integration", color: "green" },
  { from: 27, to: 30, name: "Database", color: "amber" },
  { from: 31, to: 34, name: "Real-Time", color: "cyan" },
  { from: 35, to: 40, name: "Native Features", color: "red" },
  { from: 41, to: 44, name: "Performance", color: "orange" },
  { from: 45, to: 46, name: "Testing", color: "lime" },
  { from: 47, to: 48, name: "Deployment", color: "indigo" },
  { from: 49, to: 53, name: "Professional Skills", color: "rose" },
];

function sectionFor(num) {
  return SECTIONS.find((s) => num >= s.from && num <= s.to) || SECTIONS[0];
}

function stripCommentPrefix(line) {
  // "//   some text" -> "some text"  (keeps relative indentation meaning,
  // but drops the leading // and exactly one following space if present)
  return line.replace(/^\s*\/\/ ?/, "");
}

function parseLesson(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  const filename = path.basename(filePath);
  const numMatch = filename.match(/^lesson_(\d+)_/);
  const num = parseInt(numMatch[1], 10);
  const lines = raw.split("\n");

  // ---- Opening banner: lines 0..N until the second "// ====" ----
  let bannerEnd = -1;
  let bannerSeen = 0;
  for (let i = 0; i < lines.length; i++) {
    if (/^\/\/ ={10,}/.test(lines[i])) {
      bannerSeen++;
      if (bannerSeen === 2) { bannerEnd = i; break; }
    }
  }
  const bannerLines = lines.slice(0, bannerEnd + 1);
  const titleLine = bannerLines.find((l) => /LESSON\s+\d+/.test(l)) || "";
  const titleMatch = titleLine.match(/LESSON\s+\d+\s*--\s*(.+?)\s*$/);
  const title = titleMatch ? titleMatch[1].trim() : filename;

  const philosophyIdx = bannerLines.findIndex((l) => /Teaching philosophy:/.test(l));
  let subtitle = "";
  if (philosophyIdx !== -1) {
    const philosophyLines = [];
    for (let i = philosophyIdx; i < bannerLines.length; i++) {
      const l = bannerLines[i];
      if (/^\/\/ ={10,}/.test(l)) break;
      philosophyLines.push(stripCommentPrefix(l));
    }
    subtitle = philosophyLines
      .join(" ")
      .replace(/Teaching philosophy:\s*/, "")
      .replace(/\s+/g, " ")
      .trim();
  }

  // ---- Find the [QUESTIONS] banner start ----
  const questionsIdx = lines.findIndex((l) => /\[QUESTIONS\]/.test(l));
  // its banner starts one line above (the "// ====" line right before it)
  const questionsBannerStart = questionsIdx > 0 ? questionsIdx - 1 : lines.length;

  // ---- Find the final "Lesson NN Complete!" footer banner ----
  const completeIdx = lines.findIndex((l) => /Lesson\s+\d+\s+Complete!/.test(l));
  const footerBannerStart = completeIdx > 0 ? completeIdx - 1 : lines.length;

  const mainCode = lines.slice(0, questionsBannerStart > -1 ? questionsBannerStart : lines.length).join("\n").trim();
  const questionsCode = questionsIdx > -1
    ? lines.slice(questionsBannerStart, footerBannerStart > questionsBannerStart ? footerBannerStart : lines.length).join("\n").trim()
    : "";

  // ---- Footer: bullets, "Next:" hint, "SECTION/COURSE COMPLETE" badge ----
  let takeaways = [];
  let nextHint = "";
  let milestone = "";
  if (completeIdx > -1) {
    let footerEnd = lines.length;
    for (let i = completeIdx + 1; i < lines.length; i++) {
      if (/^\/\/ ={10,}/.test(lines[i])) { footerEnd = i; break; }
    }
    const footerLines = lines.slice(completeIdx + 1, footerEnd);
    footerLines.forEach((l) => {
      const text = stripCommentPrefix(l).trim();
      if (!text) return;
      if (/^Next:/.test(text)) { nextHint = text.replace(/^Next:\s*/, ""); return; }
      if (/SECTION COMPLETE|COURSE COMPLETE/.test(text)) { milestone = text; return; }
      takeaways.push(text);
    });
  }

  const section = sectionFor(num);

  return {
    num,
    id: filename.replace(/\.tsx$/, ""),
    filename,
    title,
    subtitle,
    section: section.name,
    color: section.color,
    mainCode,
    questionsCode,
    takeaways,
    nextHint,
    milestone,
  };
}

function build() {
  const files = fs
    .readdirSync(SRC_DIR)
    .filter((f) => /^lesson_\d+_.*\.tsx$/.test(f))
    .sort();

  const lessons = files.map((f) => parseLesson(path.join(SRC_DIR, f)));

  const out = `// AUTO-GENERATED by build.js -- do not edit by hand.\n// Re-run "node build.js" after changing any lesson file.\nconst LESSONS = ${JSON.stringify(lessons, null, 0)};\n`;
  fs.writeFileSync(OUT_FILE, out, "utf8");
  console.log(`Built ${lessons.length} lessons -> ${OUT_FILE}`);
}

build();
